# Generated by Django 4.2 on 2023-05-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_d_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='vendedor_certificado',
            old_name='nombre_d_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='vendedor_promocionado',
            old_name='nombre_d_usuario',
            new_name='usuario',
        ),
    ]
