# Generated by Django 4.2 on 2023-05-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_rename_nombre_d_usuario_usuario_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='nombre_d_usuario',
        ),
        migrations.RenameField(
            model_name='vendedor_certificado',
            old_name='usuario',
            new_name='nombre_d_usuario',
        ),
        migrations.RenameField(
            model_name='vendedor_promocionado',
            old_name='usuario',
            new_name='nombre_d_usuario',
        ),
    ]
