# Generated by Django 4.2 on 2023-05-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_rename_usuario_usuario_nombre_d_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
