# Generated by Django 4.2 on 2023-05-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_delete_curso_delete_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=100)),
                ('fecha', models.DateField()),
                ('contenido', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=100)),
                ('fecha', models.DateField()),
                ('contenido', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='vendedor_certificado',
        ),
        migrations.DeleteModel(
            name='vendedor_promocionado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseñas',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_d_usuario',
            new_name='nombre',
        ),
    ]
