# Generated by Django 4.2 on 2023-05-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='autor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='subtitulo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
