# Generated by Django 4.2 on 2023-05-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_anuncio_autor_anuncio_subtitulo_blog_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='subtitulo',
        ),
    ]
