# Generated by Django 4.2 on 2023-05-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_remove_anuncio_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='autor',
        ),
    ]
