# Generated by Django 4.2 on 2023-05-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_remove_anuncio_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='tipo_de_anuncio',
            field=models.CharField(choices=[('U', 'Urgente'), ('A', 'Aviso')], default='', max_length=1),
        ),
    ]
