# Generated by Django 4.2 on 2023-05-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_anuncio_tipo_de_anuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='tipo_de_anuncio',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Aviso', 'Aviso')], default='', max_length=7),
        ),
    ]
