# Generated by Django 4.2 on 2023-05-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_alter_anuncio_tipo_de_anuncio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
