# Generated by Django 4.2 on 2023-05-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
