# Generated by Django 4.2 on 2023-05-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_delete_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='fecha',
        ),
    ]
