# Generated by Django 4.2 on 2023-05-28 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0014_remove_anuncio_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
