# Generated by Django 4.2 on 2023-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_anuncio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='fecha',
            field=models.DateField(),
        ),
    ]
